
interface ITimelineItem {
  id: number;
  groupId: number;
  title: string;
  cardTitle: string;
  cardSubtitle: string;
  cardDetailedText: string;
}
export const OrderedTimelineItems: ITimelineItem[] = [
  { id: 1, groupId: 1, title: "Mid 60s", cardTitle: "S3E10: Lantern", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Chuck reads to Jimmy from the Mabel book` },
  { id: 2, groupId: 2, title: "1973", cardTitle: "S2E7: Inflatable", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Jimmy sees his father get taken advantage of by a grifter` },
  { id: 3, groupId: 3, title: "Late 70s", cardTitle: "S4E4: Talk", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Mike builds a playground for Matty (stop once it jumps into the flashforward)` },
  { id: 4, groupId: 4, title: "Early 80s", cardTitle: "S1E3: …And the Bag's in the River", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Walt and Gretchen talk about the composition of the human body in grad school` },
  { id: 5, groupId: 4, title: "Early 80s", cardTitle: "S5E6: Wexler v. Goodman", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Kim's mom tries to pick her up from school` },
  { id: 6, groupId: 5, title: "1984", cardTitle: "S6E6: Axe and Grind", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Kim gets caught shoplifting` },
  { id: 7, groupId: 6, title: "Mid 80s", cardTitle: "S1E4: Hero", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Marco and Jimmy pull a scam with a fake Rolex` },
  { id: 8, groupId: 7, title: "1986", cardTitle: "S3E7: One Minute", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Hector tries to drown Marco to punish his brother` },
  { id: 9, groupId: 8, title: "1989", cardTitle: "S4E8: Hermanos", cardSubtitle: "Breaking Bad", cardDetailedText: `Flashback, Gus is forced to watch Max's murder when they approach Don Eladio for business` },
  { id: 10, groupId: 9, title: "1992", cardTitle: "S1E3: Nacho", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Chuck gets Jimmy out of jail in exchange for turning his life around` },
  { id: 11, groupId: 9, title: "1992", cardTitle: "S1E10: Marco", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Jimmy says goodbye to Marco before moving to Albuquerque` },
  { id: 12, groupId: 9, title: "1992", cardTitle: "S2E5: Rebecca", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Jimmy has dinner with Chuck and Rebecca after his first week working in the HHM mailroom` },
  { id: 13, groupId: 10, title: "1993", cardTitle: "S3E13: Full Measure", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Walt and a pregnant Skyler look for a new house` },
  { id: 14, groupId: 10, title: "1993", cardTitle: "S4E6: Piñata", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Jimmy starts becoming interested in law after befriending Kim in the mailroom` },
  { id: 15, groupId: 11, title: "1998", cardTitle: "Minisode: 2", cardSubtitle: "Minisode", cardDetailedText: `Wedding Day, (Hank Gets Married)` },
  { id: 16, groupId: 12, title: "1999", cardTitle: "S2E10: Klick", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Jimmy and Chuck sit by their mother's bedside as she dies` },
  { id: 17, groupId: 12, title: "1999", cardTitle: "S3E4: Sabrosito", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Hector is shown up by Gus in front of Don Eladio` },
  { id: 18, groupId: 13, title: "2001", cardTitle: "S1E8: RICO", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Jimmy passes the bar exam and is passed over for a job at HHM` },
  { id: 19, groupId: 13, title: "2001", cardTitle: "S4E10: Winner", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Jimmy is instated as a lawyer, vouched for by Chuck` },
  { id: 20, groupId: 13, title: "2001", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: `Chuck Flashback` },
  { id: 21, groupId: 13, title: "2001", cardTitle: "S3E5: Chicanery", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Chuck tries to have dinner with Rebecca and Jimmy without revealing his EHS` },
  { id: 22, groupId: 14, title: "February 2002", cardTitle: "S1E6: Five-O", cardSubtitle: "Better Call Saul", cardDetailedText: `Mid-Episode Flashback, Mike ambushes and kills Hoffman and Fensky for murdering Matty` },
  { id: 23, groupId: 15, title: "March 2002", cardTitle: "S1E6: Five-O", cardSubtitle: "Better Call Saul", cardDetailedText: `The Opening And Flashback That Comes Just Afterwards, Mike arrives in Albuquerque and visits Stacey and Kaylee, but lies to them about the circumstances of Matty's death` },
  { id: 24, groupId: 16, title: "May-June 2002", cardTitle: "S1E1: Uno", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening), right up until the skateboard twins tell Jimmy they're finishing the scam on their own` },
  { id: 25, groupId: 16, title: "May-June 2002", cardTitle: "S1E2: Mijo", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, the twins are knocked out by Tuco` },
  { id: 26, groupId: 16, title: "May-June 2002", cardTitle: "S1E1: Uno", cardSubtitle: "Better Call Saul", cardDetailedText: `Rest Of The Episode, Jimmy arrives at Tuco's house and gets pulled inside` },
  { id: 27, groupId: 16, title: "May-June 2002", cardTitle: "S1E2: Mijo", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening), rest of the episode` },
  { id: 28, groupId: 16, title: "May-June 2002", cardTitle: "S1E3: Nacho", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 29, groupId: 16, title: "May-June 2002", cardTitle: "S1E4: Hero", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 30, groupId: 16, title: "May-June 2002", cardTitle: "S1E5: Alpine Shepherd Boy", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 31, groupId: 16, title: "May-June 2002", cardTitle: "S1E6: Five-O", cardSubtitle: "Better Call Saul", cardDetailedText: `Minus The Opening And Two Flashback Scenes` },
  { id: 32, groupId: 16, title: "May-June 2002", cardTitle: "S1E7: Bingo", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 33, groupId: 16, title: "May-June 2002", cardTitle: "S1E8: RICO", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 34, groupId: 16, title: "May-June 2002", cardTitle: "S1E9: Pimento", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 35, groupId: 17, title: "July 2002", cardTitle: "S1E10: Marco", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening), up until mid-scamming montage with Marco and Jimmy` },
  { id: 36, groupId: 17, title: "July 2002", cardTitle: "S3E8: Slip", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Marco and Jimmy look at Jimmy's coin collection in Cicero` },
  { id: 37, groupId: 17, title: "July 2002", cardTitle: "S1E10: Marco", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening), from the scamming montage up until Jimmy goes inside to meet with Davis and Main` },
  { id: 38, groupId: 17, title: "July 2002", cardTitle: "S2E1: Switch", cardSubtitle: "Better Call Saul", cardDetailedText: `From Just After The Opening To After Jimmy Walks Out Of Davis And Main` },
  { id: 39, groupId: 17, title: "July 2002", cardTitle: "S1E10: Marco", cardSubtitle: "Better Call Saul", cardDetailedText: `Rest Of Episode` },
  { id: 40, groupId: 17, title: "July 2002", cardTitle: "S2E1: Switch", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening), rest of episode` },
  { id: 41, groupId: 17, title: "July 2002", cardTitle: "S2E2: Cobbler", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 42, groupId: 18, title: "August 2002", cardTitle: "S2E3: Amarillo", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 43, groupId: 18, title: "August 2002", cardTitle: "S2E4: Gloves Off", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 44, groupId: 18, title: "August 2002", cardTitle: "S2E4: Gloves Off", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Mike comes home after getting beat by Tuco` },
  { id: 45, groupId: 18, title: "August 2002", cardTitle: "S2E5: Rebecca", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 46, groupId: 18, title: "August 2002", cardTitle: "S2E6: Bali Ha'i", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 47, groupId: 19, title: "September 2002", cardTitle: "S2E7: Inflatable", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 48, groupId: 19, title: "September 2002", cardTitle: "S2E8: Fifi", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 49, groupId: 19, title: "September 2002", cardTitle: "S2E9: Nailed", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 50, groupId: 19, title: "September 2002", cardTitle: "S2E10: Klick", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 51, groupId: 19, title: "September 2002", cardTitle: "S3E1: Mabel", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 52, groupId: 19, title: "September 2002", cardTitle: "S3E2: Witness", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 53, groupId: 20, title: "October 2002", cardTitle: "S3E3: Sunk Costs", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 54, groupId: 20, title: "October 2002", cardTitle: "S3E4: Sabrosito", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 55, groupId: 21, title: "February 2003", cardTitle: "S3E5: Chicanery", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 56, groupId: 21, title: "February 2003", cardTitle: "S3E6: Off Brand", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 57, groupId: 22, title: "March 2003", cardTitle: "S3E7: Expenses", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 58, groupId: 22, title: "March 2003", cardTitle: "S3E8: Slip", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 59, groupId: 22, title: "March 2003", cardTitle: "S3E9: Fall", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 60, groupId: 22, title: "March 2003", cardTitle: "S3E10: Lantern", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 61, groupId: 22, title: "March 2003", cardTitle: "S4E1: Smoke", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 62, groupId: 23, title: "April 2003", cardTitle: "S4E2: Breathe", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 63, groupId: 23, title: "April 2003", cardTitle: "S4E3: Something Beautiful", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 64, groupId: 23, title: "April 2003", cardTitle: "S4E4: Talk", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 65, groupId: 23, title: "April 2003", cardTitle: "S4E5: Quite a Ride", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 66, groupId: 23, title: "April 2003", cardTitle: "S4E6: Piñata", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 67, groupId: 24, title: "April 2003-January 2004", cardTitle: "S4E7: Something Stupid", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 68, groupId: 25, title: "January 2004", cardTitle: "S4E8: Coushatta", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 69, groupId: 26, title: "February 2004", cardTitle: "S4E9: Wiedersehen", cardSubtitle: "Better Call Saul", cardDetailedText: `Only The Jimmy And Kim Storyline` },
  { id: 70, groupId: 27, title: "March 2004", cardTitle: "S4E10: Winner", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening), only the Jimmy and Kim storyline up until just before Jimmy’s hearing` },
  { id: 71, groupId: 27, title: "March 2004", cardTitle: "S4E9: Wiedersehen", cardSubtitle: "Better Call Saul", cardDetailedText: `Only The Cartel Storyline` },
  { id: 72, groupId: 27, title: "March 2004", cardTitle: "S4E10: Winner", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening), only the cartel storyline` },
  { id: 73, groupId: 27, title: "March 2004", cardTitle: "S4E10: Winner", cardSubtitle: "Better Call Saul", cardDetailedText: `Jimmy'S Hearing` },
  { id: 74, groupId: 28, title: "April 2004", cardTitle: "S5E1: Magic Man", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 75, groupId: 28, title: "April 2004", cardTitle: "S6E5: Black and Blue", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Werner's men make a plaque for him (I figured this was the most likely time placement)` },
  { id: 76, groupId: 28, title: "April 2004", cardTitle: "S5E2: 50% Off", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 77, groupId: 28, title: "April 2004", cardTitle: "S5E3: The Guy For This", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 78, groupId: 28, title: "April 2004", cardTitle: "S5E4: Namaste", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening), up until just before Jimmy goes to Howard's house` },
  { id: 79, groupId: 28, title: "April 2004", cardTitle: "S5E4: Namaste", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Jimmy buys bowling balls` },
  { id: 80, groupId: 28, title: "April 2004", cardTitle: "S5E4: Namaste", cardSubtitle: "Better Call Saul", cardDetailedText: `Rest Of The Episode` },
  { id: 81, groupId: 29, title: "May 2004", cardTitle: "S5E5: Dedicado a Max", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 82, groupId: 29, title: "May 2004", cardTitle: "S5E6: Wexler v. Goodman", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 83, groupId: 29, title: "May 2004", cardTitle: "S5E7: JMM", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 84, groupId: 29, title: "May 2004", cardTitle: "S5E8: Bagman", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 85, groupId: 29, title: "May 2004", cardTitle: "S5E9: Bad Choice Road", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Mike and Jimmy's walking montage split with Kim's day` },
  { id: 86, groupId: 29, title: "May 2004", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Mike and Jimmy talk about regrets` },
  { id: 87, groupId: 29, title: "May 2004", cardTitle: "S5E9: Bad Choice Road", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 88, groupId: 29, title: "May 2004", cardTitle: "S5E10: Something Unforgivable", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 89, groupId: 29, title: "May 2004", cardTitle: "S6E1: Wine and Roses", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 90, groupId: 29, title: "May 2004", cardTitle: "S6E2: Carrot and Stick", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 91, groupId: 29, title: "May 2004", cardTitle: "S6E3: Rock and Hard Place", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 92, groupId: 29, title: "May 2004", cardTitle: "S6E4: Hit and Run", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 93, groupId: 29, title: "May 2004", cardTitle: "S6E5: Black and Blue", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 94, groupId: 30, title: "June 2004", cardTitle: "S6E6: Axe and Grind", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 95, groupId: 30, title: "June 2004", cardTitle: "S6E7: Plan and Execution", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 96, groupId: 30, title: "June 2004", cardTitle: "S6E8: Point and Shoot", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 97, groupId: 30, title: "June 2004", cardTitle: "S6E9: Fun and Games", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening Montage, Kim and Jimmy go about their days while Mike cleans up the murders` },
  { id: 98, groupId: 30, title: "June 2004", cardTitle: "S6E8: Point and Shoot", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Howard’s suicide is faked` },
  { id: 99, groupId: 30, title: "June 2004", cardTitle: "S6E9: Fun and Games", cardSubtitle: "Better Call Saul", cardDetailedText: `Entire Episode (Excluding Opening), up until Kim packs up and we timeskip to the flashforward` },
  { id: 100, groupId: 31, title: "Sometime between 2004 and 2008", cardTitle: "S6E9: Fun and Games", cardSubtitle: "Better Call Saul", cardDetailedText: `Ending After The Timeskip, Saul wakes up in his slut house` },
  { id: 101, groupId: 31, title: "Sometime between 2004 and 2008", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Jimmy prepares to let Kim serve him her divorce papers` },
  { id: 102, groupId: 31, title: "Sometime between 2004 and 2008", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: `Flashback, Jimmy signs the divorce papers for Kim and she meets Jesse outside` },
  { id: 103, groupId: 31, title: "Sometime between 2004 and 2008", cardTitle: "S3E3: Sunk Costs", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Mike's shoes hang over the road from his ambush on the Salamanca truck` },
  { id: 104, groupId: 32, title: "February-August 2008", cardTitle: "Minisode 1: Good Cop", cardSubtitle: "Minisode", cardDetailedText: `Good Cop, bad cop` },
  { id: 105, groupId: 32, title: "February-August 2008", cardTitle: "Minisode 3: Twaughthammer ", cardSubtitle: "Minisode", cardDetailedText: `Twaughthammer (Jesse'S Band)` },
  { id: 106, groupId: 32, title: "February-August 2008", cardTitle: "Minisode 4: Marie's Confession", cardSubtitle: "Minisode", cardDetailedText: `Marie'S Confession, Marie Makes A Tape For Her Therapist` },
  { id: 107, groupId: 33, title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening), up until Walt tells Jesse "I am awake` },
  { id: 108, groupId: 33, title: "September 2008", cardTitle: "S3E5: Más", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Jesse buys the RV from Combo after spending all of Walt’s money at a strip club` },
  { id: 109, groupId: 33, title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: `From "I Am Awake" Until The End Of The Cooking Montage` },
  { id: 110, groupId: 33, title: "September 2008", cardTitle: "S5E14: Ozymandias", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Walt calls Skyler after his and Jesse’s first cook` },
  { id: 111, groupId: 33, title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: `From The End Of The Cooking Montage Up Until Walt Drives Away From The Brush Fire` },
  { id: 112, groupId: 33, title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Walt makes a tape for his family and points a gun at oncoming police` },
  { id: 113, groupId: 33, title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: `From Walt Pointing His Gun Up Down The Road Up Until Just Before We See Walt Cleaning Off His Money In The Dryer` },
  { id: 114, groupId: 33, title: "September 2008", cardTitle: "S1E2: Cat's in the Bag…", cardSubtitle: "Breaking Bad", cardDetailedText: `From The "Twelve Hours Before" Title Card Up Until Krazy-8 Starts Stirring In The Back Of The Rv` },
  { id: 115, groupId: 33, title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: `Rest Of The Episode` },
  { id: 116, groupId: 33, title: "September 2008", cardTitle: "S1E2Cat's: Cat's in the Bag…", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Walt passes out in the bathroom` },
  { id: 117, groupId: 34, title: "October 2008", cardTitle: "S1E2: Cat's in the Bag…", cardSubtitle: "Breaking Bad", cardDetailedText: `Starting From Krazy-8 Stirring In The Back Of The Rv Onward` },
  { id: 118, groupId: 34, title: "October 2008", cardTitle: "S1E3: … And the Bag's in the River", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 119, groupId: 34, title: "October 2008", cardTitle: "S1E4: Cancer Man", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 120, groupId: 34, title: "October 2008", cardTitle: "S1E5: Gray Matter", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 121, groupId: 34, title: "October 2008", cardTitle: "S1E6: Crazy Handful of Nothin'", cardSubtitle: "Breaking Bad", cardDetailedText: `Minus The Flashforward Parts Of The Opening` },
  { id: 122, groupId: 34, title: "October 2008", cardTitle: "S1E7: A No-Rough-Stuff-Type Deal", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 123, groupId: 35, title: "November 2008", cardTitle: "S2E1: Seven Thirty-Seven", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening), starting from when Walt and Jesse get into the car after Tuco beats up No-Doze` },
  { id: 124, groupId: 35, title: "November 2008", cardTitle: "S2E2: Grilled", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 125, groupId: 35, title: "November 2008", cardTitle: "S2E3: Bit By a Dead Bee", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 126, groupId: 35, title: "November 2008", cardTitle: "S2E4: Down", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 127, groupId: 35, title: "November 2008", cardTitle: "S2E5: Breakage", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 128, groupId: 35, title: "November 2008", cardTitle: "S2E6: Peekaboo", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 129, groupId: 36, title: "December 2008", cardTitle: "S2E7: Negro y Azul", cardSubtitle: "Breaking Bad", cardDetailedText: `Up Until Just Before Hank And The Rest Of The El Paso Agents Do Their Stakeout In The Desert` },
  { id: 130, groupId: 36, title: "December 2008", cardTitle: "S3E3: I.F.T.", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Tortuga gets beheaded by the Cousins` },
  { id: 131, groupId: 36, title: "December 2008", cardTitle: "S2E7: Negro y Azul", cardSubtitle: "Breaking Bad", cardDetailedText: `From Hank'S Stakeout Onward` },
  { id: 132, groupId: 36, title: "December 2008", cardTitle: "S2E8: Better Call Saul", cardSubtitle: "Breaking Bad", cardDetailedText: `Up Until Walt And Jesse Put The Bag Over Saul’S Head` },
  { id: 133, groupId: 36, title: "December 2008", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening` },
  { id: 134, groupId: 36, title: "December 2008", cardTitle: "S2E8: Better Call Saul", cardSubtitle: "Breaking Bad", cardDetailedText: `Walt And Jesse Threaten Saul Outside The Rv And Come To An Agreement` },
  { id: 135, groupId: 36, title: "December 2008", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: `Saul Talks With Walt And Jesse In The Rv` },
  { id: 136, groupId: 36, title: "December 2008", cardTitle: "S2E8: Better Call Saul", cardSubtitle: "Breaking Bad", cardDetailedText: `From Badger Describing Fake Heisenberg To The Police, up until just before Saul shows up at Walt’s high school` },
  { id: 137, groupId: 36, title: "December 2008", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: `Mike Gives Saul Information About Walt And Other Potential Connections` },
  { id: 138, groupId: 36, title: "December 2008", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: `Saul Visits Walt’S High School` },
  { id: 139, groupId: 36, title: "December 2008", cardTitle: "S2E8: Better Call Saul", cardSubtitle: "Breaking Bad", cardDetailedText: `Rest Of Episode` },
  { id: 140, groupId: 36, title: "December 2008", cardTitle: "S2E9: 4 Days Out", cardSubtitle: "Breaking Bad", cardDetailedText: `Up Until The Rv Finally Starts` },
  { id: 141, groupId: 36, title: "December 2008", cardTitle: "El Camino: Flashback", cardSubtitle: "El Camino", cardDetailedText: `Flashback, Walt and Jesse go to a diner after leaving the desert` },
  { id: 142, groupId: 36, title: "December 2008", cardTitle: "S2E9: 4 Days Out", cardSubtitle: "Breaking Bad", cardDetailedText: `From The Rv Starting Onward` },
  { id: 143, groupId: 36, title: "December 2008", cardTitle: "S2E10: Over", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 144, groupId: 37, title: "January 2009", cardTitle: "S3E11: Abiquiu", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Jane and Jesse visit the Georgia O'Keeffe museum` },
  { id: 145, groupId: 37, title: "January 2009", cardTitle: "El Camino: Flashback", cardSubtitle: "El Camino", cardDetailedText: `Flashback, Jane and Jesse break down on their way back from Santa Fe` },
  { id: 146, groupId: 37, title: "January 2009", cardTitle: "Minisode 5: The Break-In ", cardSubtitle: "Minisode", cardDetailedText: `The Break-In , Walt And Badger Break Into Some Ladies House` },
  { id: 147, groupId: 37, title: "January 2009", cardTitle: "Minisode 6: Live Saul Cam", cardSubtitle: "Minisode", cardDetailedText: `Live Saul Cam` },
  { id: 148, groupId: 37, title: "January 2009", cardTitle: "Minisodes 7-10: The Better Call Saul Testimonials", cardSubtitle: "Minisode", cardDetailedText: `The Better Call Saul Testimonials` },
  { id: 149, groupId: 38, title: "February 2009", cardTitle: "S2E11: Mandala", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 150, groupId: 38, title: "February 2009", cardTitle: "S2E12: Phoenix", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 151, groupId: 38, title: "February 2009", cardTitle: "S2E13: ABQ", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening), up until the end of Walt’s surgery scene` },
  { id: 152, groupId: 38, title: "February 2009", cardTitle: "S4E1: Box Cutter", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Gale convinces Gus to hire Walt` },
  { id: 153, groupId: 39, title: "March 2009", cardTitle: "S2E13: ABQ", cardSubtitle: "Breaking Bad", cardDetailedText: `Rest Of Episode` },
  { id: 154, groupId: 39, title: "March 2009", cardTitle: "S2E1: Seven Thirty-Seven", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening` },
  { id: 155, groupId: 39, title: "March 2009", cardTitle: "S2E4: Down", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening` },
  { id: 156, groupId: 39, title: "March 2009", cardTitle: "S2E10: Over", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening` },
  { id: 157, groupId: 39, title: "March 2009", cardTitle: "S2E13: ABQ", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening` },
  { id: 158, groupId: 39, title: "March 2009", cardTitle: "Minisode 11: Wayfarer 515", cardSubtitle: "Minisode", cardDetailedText: `, Wayfarer 515` },
  { id: 159, groupId: 39, title: "March 2009", cardTitle: "Minisodes 12-14, 16, 17: Better Call Saul Ads", cardSubtitle: "Minisode", cardDetailedText: `, Better Call Saul Ads` },
  { id: 160, groupId: 39, title: "March 2009", cardTitle: "S3E1: No Más", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 161, groupId: 40, title: "April 2009", cardTitle: "S3E2: Caballo Sin Nombre", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 162, groupId: 40, title: "April 2009", cardTitle: "S3E3: I.F.T.", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 163, groupId: 40, title: "April 2009", cardTitle: "S3E4: Green Light", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 164, groupId: 40, title: "April 2009", cardTitle: "S3E5: Más", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 165, groupId: 40, title: "April 2009", cardTitle: "S3E6: Sunset", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 166, groupId: 40, title: "April 2009", cardTitle: "S3E7: One Minute", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 167, groupId: 40, title: "April 2009", cardTitle: "S3E8: I See You", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 168, groupId: 40, title: "April 2009", cardTitle: "S4E8: Hermanos", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Gus visits Hector to tell him the Cousins are dead (minus the reused scene from I See You at the beginning)` },
  { id: 169, groupId: 40, title: "April 2009", cardTitle: "S3E9: Kafkaesque", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 170, groupId: 41, title: "May 2009", cardTitle: "S3E10: Fly", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 171, groupId: 41, title: "May 2009", cardTitle: "S3E11: Abiquiu", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 172, groupId: 41, title: "May 2009", cardTitle: "S3E12: Half Measures", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 173, groupId: 41, title: "May 2009", cardTitle: "S3E13: Full Measure", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 174, groupId: 41, title: "May 2009", cardTitle: "S4E1: Box Cutter", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 175, groupId: 41, title: "May 2009", cardTitle: "S4E2: Thirty-Eight Snub", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 176, groupId: 42, title: "June 2009", cardTitle: "S4E3: Open House", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 177, groupId: 42, title: "June 2009", cardTitle: "S4E4: Bullet Points", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 178, groupId: 42, title: "June 2009", cardTitle: "S4E5: Shotgun", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 179, groupId: 42, title: "June 2009", cardTitle: "S4E6: Cornered", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 180, groupId: 42, title: "June 2009", cardTitle: "S4E7: Problem Dog", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 181, groupId: 42, title: "June 2009", cardTitle: "S4E8: Hermanos", cardSubtitle: "Breaking Bad", cardDetailedText: `Minus The Opening And Gus/Max Flashback Scene` },
  { id: 182, groupId: 43, title: "July 2009", cardTitle: "S4E9: Bug", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 183, groupId: 43, title: "July 2009", cardTitle: "S4E10: Salud", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 184, groupId: 43, title: "July 2009", cardTitle: "S4E11: Crawl Space", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 185, groupId: 43, title: "July 2009", cardTitle: "S4E12: End Times", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 186, groupId: 43, title: "July 2009", cardTitle: "S4E13: Face Off", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 187, groupId: 43, title: "July 2009", cardTitle: "S5E1: Live Free or Die", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 188, groupId: 44, title: "August 2009", cardTitle: "S5E2: Madrigal", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 189, groupId: 44, title: "August 2009", cardTitle: "S5E3: Hazard Pay", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 190, groupId: 45, title: "September 2009", cardTitle: "S5E4: Fifty-One", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 191, groupId: 45, title: "September 2009", cardTitle: "S5E5: Dead Freight", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening), up until just before the heist starts` },
  { id: 192, groupId: 45, title: "September 2009", cardTitle: "S5E5: Dead Freight", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Drew Sharp rides his dirt bike` },
  { id: 193, groupId: 45, title: "September 2009", cardTitle: "S5E5: Dead Freight", cardSubtitle: "Breaking Bad", cardDetailedText: `From The Heist Onward` },
  { id: 194, groupId: 45, title: "September 2009", cardTitle: "S5E6: Buyout", cardSubtitle: "Breaking Bad", cardDetailedText: `Up Until Jesse Gets A Call And Leaves Walt Whistling After Their Cook` },
  { id: 195, groupId: 45, title: "September 2009", cardTitle: "El Camino: El Camino", cardSubtitle: "El Camino", cardDetailedText: `Opening, Mike and Jesse talk about getting out` },
  { id: 196, groupId: 45, title: "September 2009", cardTitle: "S5E6: Buyout", cardSubtitle: "Breaking Bad", cardDetailedText: `From Jesse Leaving The Cook Onward` },
  { id: 197, groupId: 45, title: "September 2009", cardTitle: "S5E7: Say My Name", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 198, groupId: 46, title: "October-March 2009", cardTitle: "S5E8: Gliding Over All", cardSubtitle: "Breaking Bad", cardDetailedText: `Up Until After The End Of The Prison Montage` },
  { id: 199, groupId: 46, title: "October-March 2009", cardTitle: "Bonus: scene", cardSubtitle: "Breaking Bad", cardDetailedText: `Chicks And Guns (Saul Tells Jesse About The Prison Murders)` },
  { id: 200, groupId: 46, title: "October-March 2009", cardTitle: "S5E8: Gliding Over All", cardSubtitle: "Breaking Bad", cardDetailedText: `Rest Of Episode` },
  { id: 201, groupId: 47, title: "March 2010", cardTitle: "S5E9: Blood Money", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 202, groupId: 47, title: "March 2010", cardTitle: "S5E10: Buried", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 203, groupId: 47, title: "March 2010", cardTitle: "S5E11: Confessions", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 204, groupId: 47, title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: `From Jesse Showing Up At Walt’S House To Burn It Down, up until Hank drives away with Jesse` },
  { id: 205, groupId: 47, title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening And Right After, Walt comes home looking for Jesse and figures out a cover story (up until just before Skyler comes home)` },
  { id: 206, groupId: 47, title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: `Start From Marie'S Therapy Session Up Until Hank Tells Her About Jesse And She’S Fine With It` },
  { id: 207, groupId: 47, title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: `Skyler Comes Home And Walt Gives His Story To Her And Jr, moves them into a hotel, talks with Saul, talks with Skyler, and talks with Jr by the hotel pool` },
  { id: 208, groupId: 47, title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: `From When Jesse Wakes Up At Hank’S House And Gives His Confession Onward` },
  { id: 209, groupId: 47, title: "March 2010", cardTitle: "S5E13: To'hajiilee", cardSubtitle: "Breaking Bad", cardDetailedText: `` },
  { id: 210, groupId: 47, title: "March 2010", cardTitle: "S5E14: Ozymandias", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening)` },
  { id: 211, groupId: 47, title: "March 2010", cardTitle: "S4E5: Quite a Ride", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Saul and Francesca discuss his escape` },
  { id: 212, groupId: 47, title: "March 2010", cardTitle: "S5E15: Granite State", cardSubtitle: "Breaking Bad", cardDetailedText: `Up Until Jesse Starts Picking His Handcuffs, just before the Walt and Saul scene starts` },
  { id: 213, groupId: 47, title: "March 2010", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: `Walt And Saul Flashback` },
  { id: 214, groupId: 47, title: "March 2010", cardTitle: "S5E15: Granite State", cardSubtitle: "Breaking Bad", cardDetailedText: `From The Start Of Walt And Saul’S Scene In Ed’S Basement Up Until Walt Arrives In New Hampshire And Decides He’Ll Walk To Town ‘Tomorrow’` },
  { id: 215, groupId: 47, title: "March 2010", cardTitle: "S6E1: Wine and Roses", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Saul's house is taken apart by the feds` },
  { id: 216, groupId: 47, title: "March 2010", cardTitle: "S5E15: Granite State", cardSubtitle: "Breaking Bad", cardDetailedText: `From Walt Arriving In New Hampshire Up Until The End Of Andrea'S Murder Scene` },
  { id: 217, groupId: 48, title: "Sometime between April and September 2010", cardTitle: "El Camino: Neil Flashback", cardSubtitle: "El Camino", cardDetailedText: `` },
  { id: 218, groupId: 48, title: "Sometime between April and September 2010", cardTitle: "El Camino: All Todd Flashbacks", cardSubtitle: "El Camino", cardDetailedText: `` },
  { id: 219, groupId: 48, title: "Sometime between April and September 2010", cardTitle: "S5E15: Granite State", cardSubtitle: "Breaking Bad", cardDetailedText: `From Walt Greeting Ed With The Newspaper Onward` },
  { id: 220, groupId: 49, title: "September 2010", cardTitle: "S5E16: Felina", cardSubtitle: "Breaking Bad", cardDetailedText: `Up Until Just Before Walt Arrives At The Diner` },
  { id: 221, groupId: 49, title: "September 2010", cardTitle: "S5E1: Live Free or Die", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Walt picks up a machine gun at a Denny's` },
  { id: 222, groupId: 49, title: "September 2010", cardTitle: "S5E9: Blood Money", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, Walt retrieves the ricin from his home` },
  { id: 223, groupId: 49, title: "September 2010", cardTitle: "S5E16: Felina", cardSubtitle: "Breaking Bad", cardDetailedText: `From Walt Leaving His House After Retrieving The Ricin Onward` },
  { id: 224, groupId: 49, title: "September 2010", cardTitle: "El Camino: Events Of Film Minus All Flashback Scenes", cardSubtitle: "El Camino", cardDetailedText: `` },
  { id: 225, groupId: 50, title: "October 2010", cardTitle: "S1E1: Uno", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Gene works at a Cinnabon` },
  { id: 226, groupId: 50, title: "October 2010", cardTitle: "S2E1: Switch", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Gene getting trapped in the mall garbage room` },
  { id: 227, groupId: 50, title: "October 2010", cardTitle: "S3E1: Mabel", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Gene leads the cops to a shoplifter and passes out afterwards` },
  { id: 228, groupId: 50, title: "October 2010", cardTitle: "S4E1: Smoke", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Gene goes to the hospital and meets Jeff the creepy taxi driver` },
  { id: 229, groupId: 50, title: "October 2010", cardTitle: "S5E1: Magic Man", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, Gene gets recognized by Jeff and resolves to deal with it` },
  { id: 230, groupId: 50, title: "October 2010", cardTitle: "S6E10: Nippy", cardSubtitle: "Better Call Saul", cardDetailedText: `` },
  { id: 231, groupId: 51, title: "November 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: `From Kim’S First Appearance Up Until Just After Her Lunch Break` },
  { id: 232, groupId: 51, title: "November 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: `From Francesca Dealing With Her Stoner Tenants Up Until Gene Sits At The Crossroads In His Car` },
  { id: 233, groupId: 51, title: "November 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: `From Just After Kim’S Lunch Break Up Until Her Secretary Pushes Through The Call From Gene And She Stares At The Phone` },
  { id: 234, groupId: 51, title: "November 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: `Scene Where Gene Calls Kim And Then Freaks Out And Smashes The Payphone Glass` },
  { id: 235, groupId: 51, title: "November 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: `From Kim Answering The Phone Call Up Until The End Of Her Coworkers Singing ‘Happy Birthday` },
  { id: 236, groupId: 51, title: "November 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: `From Gene Returning To Jeff’S House After The Phone Call Up Until The End Of His First Scam` },
  { id: 237, groupId: 52, title: "December 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: `From Gene’S Scamming Montage Up Until He Meets The Mark With Cancer` },
  { id: 238, groupId: 52, title: "December 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: `From Gene Getting A Call From Buddy About The Cancer Mark Up Until The End Of The Episode (Minus The Short Flashback Where Saul Walks Up To Walt’S High School)` },
  { id: 239, groupId: 52, title: "December 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: `From Kim Going Back To Abq Up Until Gene Flees The Cancer Patient’S House` },
  { id: 240, groupId: 52, title: "December 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: `From Gene Going Home After Escaping The Cancer Patient’S House Up To The End Of The Episode` },
  { id: 241, groupId: 52, title: "December 2010", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: `From Just After The Opening Up Until The Start Of The Walt Flashback` },
  { id: 242, groupId: 52, title: "December 2010", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: `From The End Of The Walt Flashback Up Until The Start Of The Chuck Flashback` },
  { id: 243, groupId: 52, title: "December 2010", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: `From The End Of The Chuck Flashback Up Until The End Of The Episode` },
  { id: 244, groupId: 53, title: "Years later (indeterminate)", cardTitle: "S2E5: Breakage", cardSubtitle: "Breaking Bad", cardDetailedText: `Opening, two men cross the Rio Grande and find Tuco's grill in the water` },
  { id: 245, groupId: 53, title: "Years later (indeterminate)", cardTitle: "S6E3: Rock and Hard Place", cardSubtitle: "Better Call Saul", cardDetailedText: `Opening, a flower grows where Nacho died` },
];


const formatTimelineItems = (data: ITimelineItem[]) => data.reduce((acc, { id, groupId, title, ...rest }) => {
  acc[groupId.toString()] ??= [];
  acc[groupId.toString()].push({ title, ...rest });
  return acc;
}, []);

const formatTimelineGroups = (data: ITimelineItem[]) => data.reduce((acc, { groupId, title }) => {
  acc[(groupId-1).toString()] ??= { title: title };
  return acc;
}, []);

export const TimelineDetailItems: ITimelineItem[][] = formatTimelineItems(OrderedTimelineItems);
export const TimelineDateGroups: { title: string; }[] = formatTimelineGroups(OrderedTimelineItems);
