export const TimelineItems = [
  { title: "Mid 60s" },
  { title: "1973" },
  { title: "Late 70s" },
  { title: "Early 80s" },
  { title: "1984" },
  { title: "Mid 80s" },
  { title: "1986" },
  { title: "1989" },
  { title: "1992" },
  { title: "1993" },
  { title: "1998" },
  { title: "1999" },
  { title: "2001" },
  // { title: "Mid 60s", cardTitle: "S3E10: Lantern", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Chuck reads to Jimmy from the Mabel book", },
  // { title: "1973", cardTitle: "S2E7: Inflatable", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy sees his father get taken advantage of by a grifter", },
  // { title: "Late 70s", cardTitle: "S4E4: Talk", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Mike builds a playground for Matty (stop once it jumps into the flashforward)", },
  // { title: "Early 80s", cardTitle: "S1E3: …And the Bag's in the River", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Walt and Gretchen talk about the composition of the human body in grad school", },
  // { title: "Early 80s", cardTitle: "S5E6: Wexler v. Goodman", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Kim's mom tries to pick her up from school", },
  // { title: "1984", cardTitle: "S6E6: Axe and Grind", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Kim gets caught shoplifting", },
  // { title: "Mid 80s", cardTitle: "S1E4: Hero", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Marco and Jimmy pull a scam with a fake Rolex", },
  // { title: "1986", cardTitle: "S3E7: One Minute", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Hector tries to drown Marco to punish his brother", },
  // { title: "1989", cardTitle: "S4E8: Hermanos", cardSubtitle: "Breaking Bad", cardDetailedText: "Flashback, Gus is forced to watch Max's murder when they approach Don Eladio for business", },
  // { title: "1992", cardTitle: "S1E3: Nacho", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Chuck gets Jimmy out of jail in exchange for turning his life around", },
  // { title: "1992", cardTitle: "S1E10: Marco", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy says goodbye to Marco before moving to Albuquerque", },
  // { title: "1992", cardTitle: "S2E5: Rebecca", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy has dinner with Chuck and Rebecca after his first week working in the HHM mailroom", },
  // { title: "1993", cardTitle: "S3E13: Full Measure", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Walt and a pregnant Skyler look for a new house", },
  // { title: "1993", cardTitle: "S4E6: Piñata", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy starts becoming interested in law after befriending Kim in the mailroom", },
  // { title: "1998", cardTitle: "Minisode: 2", cardSubtitle: "Minisode", cardDetailedText: "Wedding Day, (Hank Gets Married)", },
  // { title: "1999", cardTitle: "S2E10: Klick", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy and Chuck sit by their mother's bedside as she dies", },
  // { title: "1999", cardTitle: "S3E4: Sabrosito", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Hector is shown up by Gus in front of Don Eladio", },
  // { title: "2001", cardTitle: "S1E8: RICO", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy passes the bar exam and is passed over for a job at HHM", },
  // { title: "2001", cardTitle: "S4E10: Winner", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy is instated as a lawyer, vouched for by Chuck", },
  // { title: "2001", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: "Chuck Flashback", },
  // { title: "2001", cardTitle: "S3E5: Chicanery", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Chuck tries to have dinner with Rebecca and Jimmy without revealing his EHS", },
  // { title: "February 2002", cardTitle: "S1E6: Five-O", cardSubtitle: "Better Call Saul", cardDetailedText: "Mid-Episode Flashback, Mike ambushes and kills Hoffman and Fensky for murdering Matty", },
  // { title: "March 2002", cardTitle: "S1E6: Five-O", cardSubtitle: "Better Call Saul", cardDetailedText: "The Opening And Flashback That Comes Just Afterwards, Mike arrives in Albuquerque and visits Stacey and Kaylee, but lies to them about the circumstances of Matty's death", },
  // { title: "May-June 2002", cardTitle: "S1E1: Uno", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening), right up until the skateboard twins tell Jimmy they're finishing the scam on their own", },
  // { title: "May-June 2002", cardTitle: "S1E2: Mijo", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, the twins are knocked out by Tuco", },
  // { title: "May-June 2002", cardTitle: "S1E1: Uno", cardSubtitle: "Better Call Saul", cardDetailedText: "Rest Of The Episode, Jimmy arrives at Tuco's house and gets pulled inside", },
  // { title: "May-June 2002", cardTitle: "S1E2: Mijo", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening), rest of the episode", },
  // { title: "May-June 2002", cardTitle: "S1E3: Nacho", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May-June 2002", cardTitle: "S1E4: Hero", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May-June 2002", cardTitle: "S1E5: Alpine Shepherd Boy", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "May-June 2002", cardTitle: "S1E6: Five-O", cardSubtitle: "Better Call Saul", cardDetailedText: "Minus The Opening And Two Flashback Scenes", },
  // { title: "May-June 2002", cardTitle: "S1E7: Bingo", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "May-June 2002", cardTitle: "S1E8: RICO", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May-June 2002", cardTitle: "S1E9: Pimento", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "July 2002", cardTitle: "S1E10: Marco", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening), up until mid-scamming montage with Marco and Jimmy", },
  // { title: "July 2002", cardTitle: "S3E8: Slip", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Marco and Jimmy look at Jimmy's coin collection in Cicero", },
  // { title: "July 2002", cardTitle: "S1E10: Marco", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening), from the scamming montage up until Jimmy goes inside to meet with Davis and Main", },
  // { title: "July 2002", cardTitle: "S2E1: Switch", cardSubtitle: "Better Call Saul", cardDetailedText: "From Just After The Opening To After Jimmy Walks Out Of Davis And Main", },
  // { title: "July 2002", cardTitle: "S1E10: Marco", cardSubtitle: "Better Call Saul", cardDetailedText: "Rest Of Episode", },
  // { title: "July 2002", cardTitle: "S2E1: Switch", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening), rest of episode", },
  // { title: "July 2002", cardTitle: "S2E2: Cobbler", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "August 2002", cardTitle: "S2E3: Amarillo", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "August 2002", cardTitle: "S2E4: Gloves Off", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "August 2002", cardTitle: "S2E4: Gloves Off", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Mike comes home after getting beat by Tuco", },
  // { title: "August 2002", cardTitle: "S2E5: Rebecca", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "August 2002", cardTitle: "S2E6: Bali Ha'i", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "September 2002", cardTitle: "S2E7: Inflatable", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "September 2002", cardTitle: "S2E8: Fifi", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "September 2002", cardTitle: "S2E9: Nailed", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "September 2002", cardTitle: "S2E10: Klick", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "September 2002", cardTitle: "S3E1: Mabel", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "September 2002", cardTitle: "S3E2: Witness", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "October 2002", cardTitle: "S3E3: Sunk Costs", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "October 2002", cardTitle: "S3E4: Sabrosito", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "February 2003", cardTitle: "S3E5: Chicanery", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "February 2003", cardTitle: "S3E6: Off Brand", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "March 2003", cardTitle: "S3E7: Expenses", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "March 2003", cardTitle: "S3E8: Slip", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "March 2003", cardTitle: "S3E9: Fall", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "March 2003", cardTitle: "S3E10: Lantern", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "March 2003", cardTitle: "S4E1: Smoke", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "April 2003", cardTitle: "S4E2: Breathe", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "April 2003", cardTitle: "S4E3: Something Beautiful", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "April 2003", cardTitle: "S4E4: Talk", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "April 2003", cardTitle: "S4E5: Quite a Ride", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "April 2003", cardTitle: "S4E6: Piñata", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "April 2003-January 2004", cardTitle: "S4E7: Something Stupid", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "January 2004", cardTitle: "S4E8: Coushatta", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "February 2004", cardTitle: "S4E9: Wiedersehen", cardSubtitle: "Better Call Saul", cardDetailedText: "Only The Jimmy And Kim Storyline", },
  // { title: "March 2004", cardTitle: "S4E10: Winner", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening), only the Jimmy and Kim storyline up until just before Jimmy’s hearing", },
  // { title: "March 2004", cardTitle: "S4E9: Wiedersehen", cardSubtitle: "Better Call Saul", cardDetailedText: "Only The Cartel Storyline", },
  // { title: "March 2004", cardTitle: "S4E10: Winner", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening), only the cartel storyline", },
  // { title: "March 2004", cardTitle: "S4E10: Winner", cardSubtitle: "Better Call Saul", cardDetailedText: "Jimmy'S Hearing", },
  // { title: "April 2004", cardTitle: "S5E1: Magic Man", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "April 2004", cardTitle: "S6E5: Black and Blue", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Werner's men make a plaque for him (I figured this was the most likely time placement)", },
  // { title: "April 2004", cardTitle: "S5E2: 50% Off", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "April 2004", cardTitle: "S5E3: The Guy For This", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "April 2004", cardTitle: "S5E4: Namaste", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening), up until just before Jimmy goes to Howard's house", },
  // { title: "April 2004", cardTitle: "S5E4: Namaste", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy buys bowling balls", },
  // { title: "April 2004", cardTitle: "S5E4: Namaste", cardSubtitle: "Better Call Saul", cardDetailedText: "Rest Of The Episode", },
  // { title: "May 2004", cardTitle: "S5E5: Dedicado a Max", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "May 2004", cardTitle: "S5E6: Wexler v. Goodman", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May 2004", cardTitle: "S5E7: JMM", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "May 2004", cardTitle: "S5E8: Bagman", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "May 2004", cardTitle: "S5E9: Bad Choice Road", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Mike and Jimmy's walking montage split with Kim's day", },
  // { title: "May 2004", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Mike and Jimmy talk about regrets", },
  // { title: "May 2004", cardTitle: "S5E9: Bad Choice Road", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May 2004", cardTitle: "S5E10: Something Unforgivable", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "May 2004", cardTitle: "S6E1: Wine and Roses", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May 2004", cardTitle: "S6E2: Carrot and Stick", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "May 2004", cardTitle: "S6E3: Rock and Hard Place", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May 2004", cardTitle: "S6E4: Hit and Run", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "May 2004", cardTitle: "S6E5: Black and Blue", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "June 2004", cardTitle: "S6E6: Axe and Grind", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "June 2004", cardTitle: "S6E7: Plan and Execution", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "June 2004", cardTitle: "S6E8: Point and Shoot", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "June 2004", cardTitle: "S6E9: Fun and Games", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening Montage, Kim and Jimmy go about their days while Mike cleans up the murders", },
  // { title: "June 2004", cardTitle: "S6E8: Point and Shoot", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Howard’s suicide is faked", },
  // { title: "June 2004", cardTitle: "S6E9: Fun and Games", cardSubtitle: "Better Call Saul", cardDetailedText: "Entire Episode (Excluding Opening), up until Kim packs up and we timeskip to the flashforward", },
  // { title: "Sometime between 2004 and 2008", cardTitle: "S6E9: Fun and Games", cardSubtitle: "Better Call Saul", cardDetailedText: "Ending After The Timeskip, Saul wakes up in his slut house", },
  // { title: "Sometime between 2004 and 2008", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy prepares to let Kim serve him her divorce papers", },
  // { title: "Sometime between 2004 and 2008", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: "Flashback, Jimmy signs the divorce papers for Kim and she meets Jesse outside", },
  // { title: "Sometime between 2004 and 2008", cardTitle: "S3E3: Sunk Costs", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Mike's shoes hang over the road from his ambush on the Salamanca truck", },
  // { title: "February-August 2008", cardTitle: "Minisode 1: Good Cop", cardSubtitle: "Minisode", cardDetailedText: "Good Cop, bad cop", },
  // { title: "February-August 2008", cardTitle: "Minisode 3: Twaughthammer ", cardSubtitle: "Minisode", cardDetailedText: "Twaughthammer (Jesse'S Band)", },
  // { title: "February-August 2008", cardTitle: "Minisode 4: Marie's Confession", cardSubtitle: "Minisode", cardDetailedText: "Marie'S Confession, Marie Makes A Tape For Her Therapist", },
  // {
  //   title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: `Entire Episode (Excluding Opening), up until Walt tells Jesse "I am awake"`,
  // },
  // { title: "September 2008", cardTitle: "S3E5: Más", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Jesse buys the RV from Combo after spending all of Walt’s money at a strip club", },
  // { title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: `From "I Am Awake" Until The End Of The Cooking Montage`, },
  // { title: "September 2008", cardTitle: "S5E14: Ozymandias", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Walt calls Skyler after his and Jesse’s first cook", },
  // { title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: "From The End Of The Cooking Montage Up Until Walt Drives Away From The Brush Fire", },
  // { title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Walt makes a tape for his family and points a gun at oncoming police", },
  // { title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: "From Walt Pointing His Gun Up Down The Road Up Until Just Before We See Walt Cleaning Off His Money In The Dryer", },
  // { title: "September 2008", cardTitle: "S1E2: Cat's in the Bag…", cardSubtitle: "Breaking Bad", cardDetailedText: `From The "Twelve Hours Before" Title Card Up Until Krazy-8 Starts Stirring In The Back Of The Rv`, },
  // { title: "September 2008", cardTitle: "S1E1: Pilot", cardSubtitle: "Breaking Bad", cardDetailedText: "Rest Of The Episode", },
  // { title: "September 2008", cardTitle: "S1E2Cat's: Cat's in the Bag…", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Walt passes out in the bathroom", },
  // { title: "October 2008", cardTitle: "S1E2: Cat's in the Bag…", cardSubtitle: "Breaking Bad", cardDetailedText: "Starting From Krazy-8 Stirring In The Back Of The Rv Onward", },
  // { title: "October 2008", cardTitle: "S1E3: … And the Bag's in the River", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "October 2008", cardTitle: "S1E4: Cancer Man", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "October 2008", cardTitle: "S1E5: Gray Matter", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "October 2008", cardTitle: "S1E6: Crazy Handful of Nothin'", cardSubtitle: "Breaking Bad", cardDetailedText: "Minus The Flashforward Parts Of The Opening", },
  // { title: "October 2008", cardTitle: "S1E7: A No-Rough-Stuff-Type Deal", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "November 2008", cardTitle: "S2E1: Seven Thirty-Seven", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening), starting from when Walt and Jesse get into the car after Tuco beats up No-Doze", },
  // { title: "November 2008", cardTitle: "S2E2: Grilled", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "November 2008", cardTitle: "S2E3: Bit By a Dead Bee", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "November 2008", cardTitle: "S2E4: Down", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "November 2008", cardTitle: "S2E5: Breakage", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "November 2008", cardTitle: "S2E6: Peekaboo", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "December 2008", cardTitle: "S2E7: Negro y Azul", cardSubtitle: "Breaking Bad", cardDetailedText: "Up Until Just Before Hank And The Rest Of The El Paso Agents Do Their Stakeout In The Desert", },
  // { title: "December 2008", cardTitle: "S3E3: I.F.T.", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Tortuga gets beheaded by the Cousins", },
  // { title: "December 2008", cardTitle: "S2E7: Negro y Azul", cardSubtitle: "Breaking Bad", cardDetailedText: "From Hank'S Stakeout Onward", },
  // { title: "December 2008", cardTitle: "S2E8: Better Call Saul", cardSubtitle: "Breaking Bad", cardDetailedText: "Up Until Walt And Jesse Put The Bag Over Saul’S Head", },
  // { title: "December 2008", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening", },
  // { title: "December 2008", cardTitle: "S2E8: Better Call Saul", cardSubtitle: "Breaking Bad", cardDetailedText: "Walt And Jesse Threaten Saul Outside The Rv And Come To An Agreement", },
  // { title: "December 2008", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: "Saul Talks With Walt And Jesse In The Rv", },
  // { title: "December 2008", cardTitle: "S2E8: Better Call Saul", cardSubtitle: "Breaking Bad", cardDetailedText: "From Badger Describing Fake Heisenberg To The Police, up until just before Saul shows up at Walt’s high school", },
  // { title: "December 2008", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: "Mike Gives Saul Information About Walt And Other Potential Connections", },
  // { title: "December 2008", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: "Saul Visits Walt’S High School", },
  // { title: "December 2008", cardTitle: "S2E8: Better Call Saul", cardSubtitle: "Breaking Bad", cardDetailedText: "Rest Of Episode", },
  // { title: "December 2008", cardTitle: "S2E9: 4 Days Out", cardSubtitle: "Breaking Bad", cardDetailedText: "Up Until The Rv Finally Starts", },
  // { title: "December 2008", cardTitle: "El Camino: Flashback", cardSubtitle: "El Camino", cardDetailedText: "Flashback, Walt and Jesse go to a diner after leaving the desert", },
  // { title: "December 2008", cardTitle: "S2E9: 4 Days Out", cardSubtitle: "Breaking Bad", cardDetailedText: "From The Rv Starting Onward", },
  // { title: "December 2008", cardTitle: "S2E10: Over", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "January 2009", cardTitle: "S3E11: Abiquiu", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Jane and Jesse visit the Georgia O'Keeffe museum", },
  // { title: "January 2009", cardTitle: "El Camino: Flashback", cardSubtitle: "El Camino", cardDetailedText: "Flashback, Jane and Jesse break down on their way back from Santa Fe", },
  // { title: "January 2009", cardTitle: "Minisode 5: The Break-In ", cardSubtitle: "Minisode", cardDetailedText: "The Break-In , Walt And Badger Break Into Some Ladies House", },
  // { title: "January 2009", cardTitle: "Minisode 6: Live Saul Cam", cardSubtitle: "Minisode", cardDetailedText: "Live Saul Cam", },
  // { title: "January 2009", cardTitle: "Minisodes 7-10: The Better Call Saul Testimonials", cardSubtitle: "Minisode", cardDetailedText: "The Better Call Saul Testimonials", },
  // { title: "February 2009", cardTitle: "S2E11: Mandala", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "February 2009", cardTitle: "S2E12: Phoenix", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "February 2009", cardTitle: "S2E13: ABQ", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening), up until the end of Walt’s surgery scene", },
  // { title: "February 2009", cardTitle: "S4E1: Box Cutter", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Gale convinces Gus to hire Walt", },
  // { title: "March 2009", cardTitle: "S2E13: ABQ", cardSubtitle: "Breaking Bad", cardDetailedText: "Rest Of Episode", },
  // { title: "March 2009", cardTitle: "S2E1: Seven Thirty-Seven", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening", },
  // { title: "March 2009", cardTitle: "S2E4: Down", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening", },
  // { title: "March 2009", cardTitle: "S2E10: Over", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening", },
  // { title: "March 2009", cardTitle: "S2E13: ABQ", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening", },
  // { title: "March 2009", cardTitle: "Minisode 11: Wayfarer 515", cardSubtitle: "Minisode", cardDetailedText: ", Wayfarer 515", },
  // { title: "March 2009", cardTitle: "Minisodes 12-14, 16, 17: Better Call Saul Ads", cardSubtitle: "Minisode", cardDetailedText: ", Better Call Saul Ads", },
  // { title: "March 2009", cardTitle: "S3E1: No Más", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "April 2009", cardTitle: "S3E2: Caballo Sin Nombre", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "April 2009", cardTitle: "S3E3: I.F.T.", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "April 2009", cardTitle: "S3E4: Green Light", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "April 2009", cardTitle: "S3E5: Más", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "April 2009", cardTitle: "S3E6: Sunset", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "April 2009", cardTitle: "S3E7: One Minute", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "April 2009", cardTitle: "S3E8: I See You", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "April 2009", cardTitle: "S4E8: Hermanos", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Gus visits Hector to tell him the Cousins are dead (minus the reused scene from I See You at the beginning)", },
  // { title: "April 2009", cardTitle: "S3E9: Kafkaesque", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "May 2009", cardTitle: "S3E10: Fly", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "May 2009", cardTitle: "S3E11: Abiquiu", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May 2009", cardTitle: "S3E12: Half Measures", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "May 2009", cardTitle: "S3E13: Full Measure", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May 2009", cardTitle: "S4E1: Box Cutter", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "May 2009", cardTitle: "S4E2: Thirty-Eight Snub", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "June 2009", cardTitle: "S4E3: Open House", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "June 2009", cardTitle: "S4E4: Bullet Points", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "June 2009", cardTitle: "S4E5: Shotgun", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "June 2009", cardTitle: "S4E6: Cornered", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "June 2009", cardTitle: "S4E7: Problem Dog", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "June 2009", cardTitle: "S4E8: Hermanos", cardSubtitle: "Breaking Bad", cardDetailedText: "Minus The Opening And Gus/Max Flashback Scene", },
  // { title: "July 2009", cardTitle: "S4E9: Bug", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "July 2009", cardTitle: "S4E10: Salud", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "July 2009", cardTitle: "S4E11: Crawl Space", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "July 2009", cardTitle: "S4E12: End Times", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "July 2009", cardTitle: "S4E13: Face Off", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "July 2009", cardTitle: "S5E1: Live Free or Die", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "August 2009", cardTitle: "S5E2: Madrigal", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "August 2009", cardTitle: "S5E3: Hazard Pay", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "September 2009", cardTitle: "S5E4: Fifty-One", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "September 2009", cardTitle: "S5E5: Dead Freight", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening), up until just before the heist starts", },
  // { title: "September 2009", cardTitle: "S5E5: Dead Freight", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Drew Sharp rides his dirt bike", },
  // { title: "September 2009", cardTitle: "S5E5: Dead Freight", cardSubtitle: "Breaking Bad", cardDetailedText: "From The Heist Onward", },
  // { title: "September 2009", cardTitle: "S5E6: Buyout", cardSubtitle: "Breaking Bad", cardDetailedText: "Up Until Jesse Gets A Call And Leaves Walt Whistling After Their Cook", },
  // { title: "September 2009", cardTitle: "El Camino: El Camino", cardSubtitle: "El Camino", cardDetailedText: "Opening, Mike and Jesse talk about getting out", },
  // { title: "September 2009", cardTitle: "S5E6: Buyout", cardSubtitle: "Breaking Bad", cardDetailedText: "From Jesse Leaving The Cook Onward", },
  // { title: "September 2009", cardTitle: "S5E7: Say My Name", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "October-March 2009", cardTitle: "S5E8: Gliding Over All", cardSubtitle: "Breaking Bad", cardDetailedText: "Up Until After The End Of The Prison Montage", },
  // { title: "October-March 2009", cardTitle: "Bonus: scene", cardSubtitle: "Breaking Bad", cardDetailedText: "Chicks And Guns (Saul Tells Jesse About The Prison Murders)", },
  // { title: "October-March 2009", cardTitle: "S5E8: Gliding Over All", cardSubtitle: "Breaking Bad", cardDetailedText: "Rest Of Episode", },
  // { title: "March 2010", cardTitle: "S5E9: Blood Money", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "March 2010", cardTitle: "S5E10: Buried", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "March 2010", cardTitle: "S5E11: Confessions", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: "From Jesse Showing Up At Walt’S House To Burn It Down, up until Hank drives away with Jesse", },
  // { title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening And Right After, Walt comes home looking for Jesse and figures out a cover story (up until just before Skyler comes home)", },
  // { title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: "Start From Marie'S Therapy Session Up Until Hank Tells Her About Jesse And She’S Fine With It", },
  // { title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: "Skyler Comes Home And Walt Gives His Story To Her And Jr, moves them into a hotel, talks with Saul, talks with Skyler, and talks with Jr by the hotel pool", },
  // { title: "March 2010", cardTitle: "S5E12: Rabid Dog", cardSubtitle: "Breaking Bad", cardDetailedText: "From When Jesse Wakes Up At Hank’S House And Gives His Confession Onward", },
  // { title: "March 2010", cardTitle: "S5E13: To'hajiilee", cardSubtitle: "Breaking Bad", cardDetailedText: "", },
  // { title: "March 2010", cardTitle: "S5E14: Ozymandias", cardSubtitle: "Breaking Bad", cardDetailedText: "Entire Episode (Excluding Opening)", },
  // { title: "March 2010", cardTitle: "S4E5: Quite a Ride", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Saul and Francesca discuss his escape", },
  // { title: "March 2010", cardTitle: "S5E15: Granite State", cardSubtitle: "Breaking Bad", cardDetailedText: "Up Until Jesse Starts Picking His Handcuffs, just before the Walt and Saul scene starts", },
  // { title: "March 2010", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: "Walt And Saul Flashback", },
  // { title: "March 2010", cardTitle: "S5E15: Granite State", cardSubtitle: "Breaking Bad", cardDetailedText: "From The Start Of Walt And Saul’S Scene In Ed’S Basement Up Until Walt Arrives In New Hampshire And Decides He’Ll Walk To Town ‘Tomorrow’", },
  // { title: "March 2010", cardTitle: "S6E1: Wine and Roses", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Saul's house is taken apart by the feds", },
  // { title: "March 2010", cardTitle: "S5E15: Granite State", cardSubtitle: "Breaking Bad", cardDetailedText: "From Walt Arriving In New Hampshire Up Until The End Of Andrea'S Murder Scene", },
  // { title: "April-September 2010", cardTitle: "El Camino: Neil Flashback", cardSubtitle: "El Camino", cardDetailedText: "", },
  // { title: "April-September 2010", cardTitle: "El Camino: All Todd Flashbacks", cardSubtitle: "El Camino", cardDetailedText: "", },
  // { title: "April-September 2010", cardTitle: "S5E15: Granite State", cardSubtitle: "Breaking Bad", cardDetailedText: "From Walt Greeting Ed With The Newspaper Onward", },
  // { title: "September 2010", cardTitle: "S5E16: Felina", cardSubtitle: "Breaking Bad", cardDetailedText: "Up Until Just Before Walt Arrives At The Diner", },
  // { title: "September 2010", cardTitle: "S5E1: Live Free or Die", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Walt picks up a machine gun at a Denny's", },
  // { title: "September 2010", cardTitle: "S5E9: Blood Money", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Walt retrieves the ricin from his home", },
  // { title: "September 2010", cardTitle: "S5E16: Felina", cardSubtitle: "Breaking Bad", cardDetailedText: "From Walt Leaving His House After Retrieving The Ricin Onward", },
  // { title: "September 2010", cardTitle: "El Camino: Events Of Film Minus All Flashback Scenes", cardSubtitle: "El Camino", cardDetailedText: "", },
  // { title: "October 2010", cardTitle: "S1E1: Uno", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Gene works at a Cinnabon", },
  // { title: "October 2010", cardTitle: "S2E1: Switch", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Gene getting trapped in the mall garbage room", },
  // { title: "October 2010", cardTitle: "S3E1: Mabel", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Gene leads the cops to a shoplifter and passes out afterwards", },
  // { title: "October 2010", cardTitle: "S4E1: Smoke", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Gene goes to the hospital and meets Jeff the creepy taxi driver", },
  // { title: "October 2010", cardTitle: "S5E1: Magic Man", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Gene gets recognized by Jeff and resolves to deal with it", },
  // { title: "October 2010", cardTitle: "S6E10: Nippy", cardSubtitle: "Better Call Saul", cardDetailedText: "", },
  // { title: "November 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: "From Kim’S First Appearance Up Until Just After Her Lunch Break", },
  // { title: "November 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: "From Francesca Dealing With Her Stoner Tenants Up Until Gene Sits At The Crossroads In His Car", },
  // { title: "November 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: "From Just After Kim’S Lunch Break Up Until Her Secretary Pushes Through The Call From Gene And She Stares At The Phone", },
  // { title: "November 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: "Scene Where Gene Calls Kim And Then Freaks Out And Smashes The Payphone Glass", },
  // { title: "November 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: "From Kim Answering The Phone Call Up Until The End Of Her Coworkers Singing ‘Happy Birthday", },
  // { title: "November 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: "From Gene Returning To Jeff’S House After The Phone Call Up Until The End Of His First Scam", },
  // { title: "December 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: "From Gene’S Scamming Montage Up Until He Meets The Mark With Cancer", },
  // { title: "December 2010", cardTitle: "S6E11: Breaking Bad", cardSubtitle: "Better Call Saul", cardDetailedText: "From Gene Getting A Call From Buddy About The Cancer Mark Up Until The End Of The Episode (Minus The Short Flashback Where Saul Walks Up To Walt’S High School)", },
  // { title: "December 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: "From Kim Going Back To Abq Up Until Gene Flees The Cancer Patient’S House", },
  // { title: "December 2010", cardTitle: "S6E12: Waterworks", cardSubtitle: "Better Call Saul", cardDetailedText: "From Gene Going Home After Escaping The Cancer Patient’S House Up To The End Of The Episode", },
  // { title: "December 2010", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: "From Just After The Opening Up Until The Start Of The Walt Flashback", },
  // { title: "December 2010", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: "From The End Of The Walt Flashback Up Until The Start Of The Chuck Flashback", },
  // { title: "December 2010", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: "From The End Of The Chuck Flashback Up Until The End Of The Episode", },
  // { title: "Years later (indeterminate)", cardTitle: "S2E5: Breakage", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, two men cross the Rio Grande and find Tuco's grill in the water", },
  // { title: "Years later (indeterminate)", cardTitle: "S6E3: Rock and Hard Place", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, a flower grows where Nacho died", },
];

export const TimelineDetailItems = [
  [{ title: "Mid 60s", cardTitle: "S3E10: Lantern", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Chuck reads to Jimmy from the Mabel book", }],
  [{ title: "1973", cardTitle: "S2E7: Inflatable", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy sees his father get taken advantage of by a grifter", }],
  [{ title: "Late 70s", cardTitle: "S4E4: Talk", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Mike builds a playground for Matty (stop once it jumps into the flashforward)", }],
  [{ title: "Early 80s", cardTitle: "S1E3: …And the Bag's in the River", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Walt and Gretchen talk about the composition of the human body in grad school", },
  { title: "Early 80s", cardTitle: "S5E6: Wexler v. Goodman", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Kim's mom tries to pick her up from school", }],
  [{ title: "1984", cardTitle: "S6E6: Axe and Grind", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Kim gets caught shoplifting", }],
  [{ title: "Mid 80s", cardTitle: "S1E4: Hero", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Marco and Jimmy pull a scam with a fake Rolex", }],
  [{ title: "1986", cardTitle: "S3E7: One Minute", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Hector tries to drown Marco to punish his brother", }],
  [{ title: "1989", cardTitle: "S4E8: Hermanos", cardSubtitle: "Breaking Bad", cardDetailedText: "Flashback, Gus is forced to watch Max's murder when they approach Don Eladio for business", }],
  [{ title: "1992", cardTitle: "S1E3: Nacho", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Chuck gets Jimmy out of jail in exchange for turning his life around", },
  { title: "1992", cardTitle: "S1E10: Marco", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy says goodbye to Marco before moving to Albuquerque", },
  { title: "1992", cardTitle: "S2E5: Rebecca", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy has dinner with Chuck and Rebecca after his first week working in the HHM mailroom", }],
  [{ title: "1993", cardTitle: "S3E13: Full Measure", cardSubtitle: "Breaking Bad", cardDetailedText: "Opening, Walt and a pregnant Skyler look for a new house", },
  { title: "1993", cardTitle: "S4E6: Piñata", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy starts becoming interested in law after befriending Kim in the mailroom", }],
  [{ title: "1998", cardTitle: "Minisode: 2", cardSubtitle: "Minisode", cardDetailedText: "Wedding Day, (Hank Gets Married)", }],
  [{ title: "1999", cardTitle: "S2E10: Klick", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy and Chuck sit by their mother's bedside as she dies", },
  { title: "1999", cardTitle: "S3E4: Sabrosito", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Hector is shown up by Gus in front of Don Eladio", }],
  [{ title: "2001", cardTitle: "S1E8: RICO", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy passes the bar exam and is passed over for a job at HHM", },
  { title: "2001", cardTitle: "S4E10: Winner", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Jimmy is instated as a lawyer, vouched for by Chuck", },
  { title: "2001", cardTitle: "S6E13: Saul Gone", cardSubtitle: "Better Call Saul", cardDetailedText: "Chuck Flashback", },
  { title: "2001", cardTitle: "S3E5: Chicanery", cardSubtitle: "Better Call Saul", cardDetailedText: "Opening, Chuck tries to have dinner with Rebecca and Jimmy without revealing his EHS", }],
]
